---
- name: configure VLANs
  hosts: arista
  gather_facts: false

  tasks:

  - name: use vlans resource module
    arista.eos.vlans:
      state: "{{ vlan_rm_state }}"
      config:
        - name: desktops
          vlan_id: 20
        - name: servers
          vlan_id: 30
        - name: printers
          vlan_id: 40
        - name: DMZ
          vlan_id: 50
      register: vlan_config
  
  - name: print vlan config
    debug:
      var: vlan_config | to_nice_yaml
    when: vlan_rm_state == "gathered"
    