---
- name: Check Golden Config Compliance
  hosts: cisco
  gather_facts: true

  tasks:
    - name: check snmp-server configs are present
      cisco.ios.snmp_server:
        config: "{{ snmp.config }}"
        state: "{{ snmp.state }}"
      check_mode: true
      register: snmp_compliance

    - name: set snmp compliance status
      ansible.builtin.set_fact:
        snmp_compliance: "{{ snmp_compliance.changed }}"
        snmp_deviation_fix: "{{ snmp_compliance.commands }}"
  
    - name: print snmp compliance status
      debug:
        msg: 
          - "snmp_compliance {{ snmp_compliance }}"
          - "snmp fix commands {{ snmp_deviation_fix }}"

    - name: check ntp configs are present
      cisco.ios.ios_ntp_global:
        config: "{{ ntp.config }}"
        state: "{{ ntp.state }}"
      check_mode: true
      register: ntp_compliance

    - name: set ntp compliance status
      ansible.builtin.set_fact:
        ntp_compliance: "{{ ntp_compliance.changed }}"
        ntp_deviation_fix: "{{ ntp_compliance.commands }}"
  
    - name: print ntp compliance status
      debug:
        msg: 
          - "ntp_compliance {{ ntp_compliance }}"
          - "ntp fix commands {{ ntp_deviation_fix }}"

    - name: check acl configs are present
      cisco.ios.ios_acls:
        config: "{{ acl.config }}"
        state: "{{ acl.state }}"
      check_mode: true
      register: acl_compliance

    - name: set acl compliance status
      ansible.builtin.set_fact:
        acl_compliance: "{{ acl_compliance.changed }}"
        acl_deviation_fix: "{{ acl_compliance.commands }}"
  
    - name: print acl compliance status
      debug:
        msg: 
          - "acl_compliance {{ acl_compliance }}"
          - "acl fix commands {{ acl_deviation_fix }}"

    - name: Generate Report Date Time
      set_fact:
        datetime: "{{ ansible_date_time.date }}_{{ ansible_date_time.time |  replace(':','-') }}" 
      delegate_to: localhost
      delegate_facts: true
      run_once: true

    - name: Copy report file to report server
      ansible.builtin.template:
        src: templates/cisco_compliance_report.j2
        dest: "/opt/ansible/reports/network_compliance/network_compliance_Report_{{ hostvars['localhost'].datetime }}.html"
      delegate_to: localhost  
      run_once: yes

    - name: Print Report location
      debug:
        msg: "http://{{ report_server }}/network_compliance/network_compliance_Report_{{ hostvars['localhost'].datetime }}.html"
      run_once: yes