snmp:
  config:
    communities:
    -   acl_v4: snmpACL
        name: mergedComm
        rw: true
    groups:
    -   group: mergedGroup
        version: v3
        version_option: auth
    hosts:
    -   community_string: mergedComm
        host: 172.16.2.9
        informs: true
        traps:
        - msdp
        - stun
        - pki
        version: 2c
    traps:
        cef:
            enable: true
            inconsistency: true
            peer_fib_state_change: true
            peer_state_change: true
            resource_failure: true
        msdp: true
        ospf:
            cisco_specific:
                error: true
                lsa: true
                retransmit: true
                state_change:
                    nssa_trans_change: true
                    shamlink:
                        interface: true
                        neighbor: true
            error: true
            lsa: true
            retransmit: true
            state_change: true
        syslog: true
        tty: true
    users:
    -   acl_v4: '24'
        group: dev
        username: snmpUser
        version: v1
  state: merged

ntp:
  config:
    logging: true
    peers:
      - peer: 172.16.1.10
        version: 2
      - key: 2
        minpoll: 5
        peer: 172.16.1.11
        prefer: true
        version: 2
    servers:
      - server: 172.16.1.12
        version: 2
      - server: 172.16.1.13
        version: 2
  state: merged

# acl:
#   config:
#     - afi: ipv4
#       acls:
#       - name: std_den
#         acl_type: standard
#         aces:
#         - grant: deny
#           source:
#             address: 192.168.1.200
#         - grant: deny
#           source:
#             address: 192.168.2.0
#             wildcard_bits: 0.0.0.255
#       - name: 110
#         aces:
#         - sequence: 10
#           protocol_options:
#             icmp:
#               traceroute: true
#         - grant: deny
#           protocol_options:
#             tcp:
#               ack: true
#           source:
#             host: 198.51.100.0
#           destination:
#             host: 198.51.110.0
#             port_protocol:
#               eq: telnet
#       - name: BLK_3_WEB
#         acl_type: extended
#         aces:
#         - grant: deny
#           protocol_options:
#             tcp:
#               fin: true
#           source:
#             address: 192.0.2.0
#             wildcard_bits: 0.0.0.255
#           destination:
#             address: 192.0.3.0
#             wildcard_bits: 0.0.0.255
#             port_protocol:
#               eq: www
#           option:
#             traceroute: true
#           ttl:
#             eq: 10
#       - name: BLK_101_TN_W
#         aces:
#         - remarks:
#           - "remarks for extended ACL 1"
#           - "check ACL"
#         - grant: deny
#           protocol_options:
#             tcp:
#               ack: true
#           source:
#             address: 198.51.100.0
#             wildcard_bits: 0.0.0.255
#           destination:
#             address: 198.51.101.0
#             wildcard_bits: 0.0.0.255
#             port_protocol:
#               eq: telnet
#           tos:
#             service_value: 12
#         - grant: deny
#           protocol_options:
#             tcp:
#               ack: true
#           source:
#             address: 192.0.3.0
#             wildcard_bits: 0.0.0.255
#           destination:
#             address: 192.0.4.0
#             wildcard_bits: 0.0.0.255
#             port_protocol:
#               eq: www
#           dscp: ef
#           ttl:
#             lt: 20
#       - name: ACL_MGMT
#         acl_type: extended
#         aces:
#         - grant: permit
#           source:
#             any: true
#           destination:
#             address: 172.16.100.0
#             wildcard_bits: 0.0.0.255
#         - grant: permit
#           source:
#             any: true
#           destination:
#             address: 192.168.200.0
#             wildcard_bits: 0.0.0.255
#     - afi: ipv6
#       acls:
#       - name: TLV6_TRAFFIC
#         aces:
#         - grant: deny
#           protocol_options:
#             tcp:
#               ack: true
#           source:
#             any: true
#             port_protocol:
#               eq: www
#           destination:
#             any: true
#             port_protocol:
#               eq: telnet
#           dscp: af11    
#   state: merged

# simple ACL
acl:
  config:
    - afi: ipv4
      acls:
      - name: ACL_MGMT
        acl_type: extended
        aces:
        - grant: permit
          source:
            any: true
          destination:
            address: 172.16.100.0
            wildcard_bits: 0.0.0.255
        - grant: permit
          source:
            any: true
          destination:
            address: 192.168.200.0
            wildcard_bits: 0.0.0.255
    - afi: ipv6
      acls:
      - name: TLV6_TRAFFIC
        aces:
        - grant: deny
          protocol_options:
            tcp:
              ack: true
          source:
            any: true
            port_protocol:
              eq: www
          destination:
            any: true
            port_protocol:
              eq: telnet
          dscp: af11    
  state: replaced

